-- ============================================================
-- DIMENSION EXPLORATION
-- ============================================================

-- Explore all the countries our customers come from
SELECT DISTINCT(country)
FROM gold.dim_customers;


-- Explore all product categories, subcategories, and products
SELECT DISTINCT category_name, sub_category_name,product_name
FROM gold.dim_products
ORDER BY 1,2,3; 
-- 5 categories
-- 37 subcategories
-- 295 products




-- ============================================================
-- DATE EXPLORATION
-- ============================================================

-- Finding the date of the first and last order
-- Also finding how many months of sales data is available

SELECT 
  MIN(order_date) AS first_order_date,
  MAX(order_date) AS last_order_date,
  ROUND((MAX(order_date) - MIN(order_date))/30) AS month_range
FROM gold.fact_sales;


-- Finding the age boundaries of our customers
-- Oldest customer and youngest customer

SELECT 
  DATE_PART('year', AGE(CURRENT_DATE, MIN(birth_date))) AS oldest_age,
  DATE_PART('year', AGE(CURRENT_DATE, MAX(birth_date))) AS youngest_age
FROM gold.dim_customers;




-- ============================================================
-- MEASURES EXPLORATION
-- ============================================================

-- Find the Total Sales
SELECT SUM(sales)
FROM gold.fact_sales;


-- Find how many items are sold
SELECT SUM(quantity)
FROM gold.fact_sales;


-- Find the average selling price
SELECT AVG(price)
FROM gold.fact_sales;


-- Find the Total nuber of Orders
SELECT COUNT(DISTINCT order_number)
FROM gold.fact_sales;


-- Find the total number of products
SELECT COUNT(*)
FROM gold.dim_products;


-- Find the total number of customers
SELECT COUNT(*)
FROM gold.dim_customers;


-- Find the total number of customers that has placed an order
SELECT COUNT(DISTINCT customer_key)
FROM gold.fact_sales;


-- Report showing all major business metrics
SELECT 'Total Sales' as measure_name, SUM(sales) as measure_value
FROM gold.fact_sales

UNION ALL

SELECT 'Total Items Sold' as measure_name, SUM(QUANTITY) as measure_value
FROM gold.fact_sales

UNION ALL

SELECT 'Average Selling Price' as measure_name, ROUND(AVG(price)) as measure_value
FROM gold.fact_sales

UNION ALL

SELECT 'Total no. of orders' as measure_name, COUNT(DISTINCT order_number) as measure_value
FROM gold.fact_sales



UNION ALL

SELECT 'Total no. of products' as measure_name, COUNT(*) as measure_value
FROM gold.dim_products

UNION ALL

SELECT 'Total no. of customers' as measure_name, COUNT(*) as measure_value
FROM gold.dim_customers

UNION ALL
  
SELECT 'No. of customers that placed an order' as measure_name, COUNT(DISTINCT customer_key) as measure_value
FROM gold.fact_sales;




-- ============================================================
-- MAGNITUDE EXPLORATION
-- ============================================================

-- Find total customers by countries
SELECT country, COUNT(*)
FROM gold.dim_customers
GROUP BY country;


-- Find total customers by gender
SELECT gender, COUNT(*)
FROM gold.dim_customers
GROUP BY gender;


-- Find total products by category
SELECT category_name, COUNT(*)
FROM gold.dim_products
GROUP BY category_name;


-- What is the average costs in each category?
SELECT category_name, ROUND(AVG(cost),2)
FROM gold.dim_products
GROUP BY category_name;


-- What is the total revenue generated for each category?
SELECT category_name, SUM(sales)
FROM gold.fact_sales 
LEFT JOIN gold.dim_products 
USING (product_key)
GROUP BY category_name;


-- Find total revenue generated by each customer
SELECT customer_id, SUM(sales)
FROM gold.fact_sales 
LEFT JOIN gold.dim_customers 
USING (customer_key)
GROUP BY customer_id;


-- What is the distribution of sold items across countries?
SELECT country, COUNT(*)
FROM gold.fact_sales 
LEFT JOIN gold.dim_customers 
USING (customer_key)
GROUP BY country;




-- ============================================================
-- RANKING EXPLORATION
-- ============================================================

-- Which 5 products generate the highest revenue?
SELECT product_name, SUM(sales)
FROM gold.fact_sales
LEFT JOIN gold.dim_products
USING(product_key)
group by product_name
ORDER BY SUM(sales) DESC
LIMIT 5;


-- What are the 5 worst-performing products in terms of sales?
SELECT product_name, SUM(sales)
FROM gold.fact_sales
LEFT JOIN gold.dim_products
USING(product_key)
group by product_name
ORDER BY SUM(sales) 
LIMIT 5;
