/*
===============================================================================
Product Report
===============================================================================

Purpose:
- This report consolidates key product metrics and behaviors.

Highlights:
1. Gathers essential product information:
   - Product name
   - Category
   - Subcategory
   - Cost

2. Segments products by revenue:
   - High Performer
   - Mid-Range
   - Low Performer

3. Aggregates product-level metrics:
   - Total orders
   - Total sales/revenue
   - Total quantity sold
   - Total unique customers
   - Order lifespan (in months)

4. Calculates valuable KPIs:
   - Recency (months since last sale)
   - Average Order Revenue (AOR)
   - Average Monthly Revenue
===============================================================================
*/

CREATE VIEW gold.report_products AS (

    -- =========================================================================
    -- BASE QUERY
    -- =========================================================================
    -- Combines sales transactions with product information.
    -- Only transactions with a valid order date are included.
    
    WITH base_query AS (
        SELECT
            order_number,
            order_date,
            customer_key,
            sales,
            quantity,
            product_id,
            product_key,
            product_number,
            product_name,
            category_name,
            sub_category_name,
            cost

        FROM gold.fact_sales

        LEFT JOIN gold.dim_products
            USING (product_key)

        WHERE order_date IS NOT NULL
    ),

    -- =========================================================================
    -- PRODUCT AGGREGATIONS
    -- =========================================================================
    -- Aggregates sales data at the product level and calculates:
    -- - Total orders
    -- - Total revenue
    -- - Total quantity sold
    -- - Total unique customers
    -- - Order lifespan
    -- - Recency

    product_aggregations AS (
        SELECT
            product_key,
            product_id,
            product_number,
            product_name,
            cost,
            category_name,
            sub_category_name,

            -- Total number of unique orders
            COUNT(DISTINCT order_number) AS total_orders,

            -- Total revenue generated by the product
            SUM(sales) AS revenue,

            -- Total quantity sold
            SUM(quantity) AS total_quantity,

            -- Number of unique customers who purchased the product
            COUNT(DISTINCT customer_key) AS total_customers,

            -- Number of months between the first and last sale
            EXTRACT(YEAR FROM AGE(MAX(order_date), MIN(order_date))) * 12
                + EXTRACT(MONTH FROM AGE(MAX(order_date), MIN(order_date)))
                AS order_lifespan,

            -- Number of months since the product's last sale
            EXTRACT(MONTH FROM AGE(MAX(order_date))) AS recency

        FROM base_query

        GROUP BY
            product_key,
            product_id,
            product_number,
            product_name,
            cost,
            category_name,
            sub_category_name
    )

    -- =========================================================================
    -- FINAL REPORT
    -- =========================================================================
    -- Adds product revenue segmentation and calculated KPIs.

    SELECT
        product_key,
        product_id,
        product_number,
        product_name,
        cost,

        -- Categorize products based on total revenue
        CASE
            WHEN revenue > 50000 THEN 'High Performer'
            WHEN revenue > 10000 THEN 'Mid-Range'
            ELSE 'Low Performer'
        END AS revenue_category,

        category_name,
        sub_category_name,
        revenue,
        total_orders,

        -- Average Order Revenue (AOR)
        CASE
            WHEN total_orders = 0 THEN 0
            ELSE revenue / total_orders
        END AS AOR,

        -- Average monthly revenue generated by the product
        CASE
            WHEN order_lifespan = 0 THEN 0
            ELSE ROUND(revenue / order_lifespan)
        END AS avg_monthly_revenue,

        total_quantity,
        total_customers,
        recency,
        order_lifespan

    FROM product_aggregations
);

