/*
===============================================================================
Customer Report
===============================================================================

Purpose:
- This report consolidates key customer metrics and behaviors.

Highlights:
1. Gathers essential customer and transaction information:
   - Customer name
   - Age
   - Order details

2. Segments customers into:
   - VIP
   - Regular
   - New

3. Groups customers into age categories:
   - Under 20
   - 20-29
   - 30-39
   - 40-49
   - 50 and above

4. Aggregates customer-level metrics:
   - Total orders
   - Total sales
   - Total quantity purchased
   - Total products
   - Customer lifespan (in months)

5. Calculates valuable KPIs:
   - Recency (months since last order)
   - Average Order Value (AOV)
   - Average Monthly Spend
===============================================================================
*/

CREATE VIEW gold.report_customers AS (

    -- =========================================================================
    -- BASE QUERY
    -- =========================================================================
    -- Combines sales transactions with customer information.
    -- Only transactions with a valid order date are included.

    WITH base_query AS (
        SELECT
            order_number,
            product_key,
            order_date,
            sales,
            quantity,
            dim_customers.customer_key,
            customer_no,
            CONCAT(first_name, ' ', last_name) AS name,
            EXTRACT(YEAR FROM AGE(birth_date)) AS age

        FROM gold.fact_sales

        LEFT JOIN gold.dim_customers
            USING (customer_key)

        WHERE order_date IS NOT NULL
    ),

    -- =========================================================================
    -- CUSTOMER AGGREGATIONS
    -- =========================================================================
    -- Aggregates transaction-level data at the customer level.
    -- Calculates sales, order, quantity, product, lifespan, and recency metrics.

    customer_aggregation AS (
        SELECT
            customer_no,
            name,
            age,

            -- Total number of unique orders
            COUNT(DISTINCT order_number) AS total_orders,

            -- Total revenue generated by the customer
            SUM(sales) AS total_sales,

            -- Total quantity of products purchased
            SUM(quantity) AS total_quantity,

            -- Number of unique products purchased
            COUNT(DISTINCT product_key) AS total_products,

            -- Number of months between the customer's first and last order
            EXTRACT(YEAR FROM AGE(MAX(order_date), MIN(order_date))) * 12
                + EXTRACT(MONTH FROM AGE(MAX(order_date), MIN(order_date)))
                AS order_lifespan,

            -- Number of months since the customer's last order
            EXTRACT(MONTH FROM AGE(MAX(order_date))) AS recency_in_months

        FROM base_query

        GROUP BY
            customer_no,
            name,
            age
    )

    -- =========================================================================
    -- FINAL CUSTOMER REPORT
    -- =========================================================================
    -- Adds customer segmentation, age groups, and calculated KPIs.

    SELECT
        customer_no,
        name,
        age,

        -- Categorize customers based on age
        CASE
            WHEN age < 20 THEN 'Under 20'
            WHEN age BETWEEN 20 AND 29 THEN '20-29'
            WHEN age BETWEEN 30 AND 39 THEN '30-39'
            WHEN age BETWEEN 40 AND 49 THEN '40-49'
            ELSE '50 and above'
        END AS age_group,

        -- Categorize customers based on lifespan and total spending
        CASE
            WHEN order_lifespan < 12 THEN 'New'
            WHEN total_sales > 5000 THEN 'VIP'
            ELSE 'Regular'
        END AS customer_category,

        recency_in_months,

        -- Average Order Value (AOV)
        CASE
            WHEN total_sales = 0 THEN 0
            ELSE total_sales / total_orders
        END AS avg_order_value,

        -- Average monthly spending
        CASE
            WHEN order_lifespan = 0 THEN 0
            ELSE ROUND(total_sales / order_lifespan)
        END AS avg_monthly_spend,

        total_orders,
        total_sales,
        total_quantity,
        total_products,
        order_lifespan

    FROM customer_aggregation
);
